auth_request /iocaine_auth;
auth_request_set $iocaine_victim $upstream_http_x_iocaine_victim;
error_page 421 = @iocaine_garbage;

location = /iocaine_auth {
  internal;
  proxy_pass http://iocaine;
  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_pass_request_body off;
  proxy_pass_request_headers on;
  proxy_set_header Content-Length "";
  proxy_set_header X-Iocaine-Victim "";
  proxy_set_header X-Original-Path $request_uri;
}

location @iocaine_garbage {
  proxy_pass http://iocaine;
  auth_request off;
  proxy_set_header Host $http_host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_pass_request_body off;
  proxy_set_header Content-Length "";
  proxy_set_header X-Iocaine-Victim "1";
  proxy_set_header X-Original-Path $request_uri;
}

